Feature/about us
Milton0123/RefactoringLife4 pull request #59
Opened 2023-09-07 15:03 UTC by jereswaxd

Se creo la activity de About Us con dos recycler view en los que se muestran las imágenes de los miembros de desarrollo
![image](https://github.com/Milton0123/RefactoringLife4/assets/94081789/c2088b55-b8b0-4971-a0e4-54feed69fa94)

estos se escribieron de forma directa en serviceImp aun así siguiendo toda la arquitectura, para subir las imagenes a internet se uso https://imgbb.com/
![image](https://github.com/Milton0123/RefactoringLife4/assets/94081789/25578b30-cd22-4407-baab-2f64fb9fb41c)

también se añadió la funcionalidad que al hacer click en una imagen se haga zoom pasando el link de la imagen por el onclick del adaptar y después pintándolo en la pantalla
![image](https://github.com/Milton0123/RefactoringLife4/assets/94081789/3937a6fc-ab07-4425-83df-c7ae595f9774)

2023-09-07 17:33 UTC, Milton0123 requested changes

2023-09-07 17:33 UTC, Milton0123 commented on app/src/main/java/com/example/refactoringlife4/model/service/UsService.kt
espacio en blanco

2023-09-07 17:33 UTC, Milton0123 commented on app/src/main/res/layout/item_rv_us_about_us.xml
espacio en blanco

2023-09-07 17:33 UTC, Milton0123 commented on app/src/main/res/layout/item_rv_us_members.xml
espacio en blanco

2023-09-07 17:36 UTC, jereswaxd commented on app/src/main/res/layout/item_rv_us_members.xml
solucionado

2023-09-07 17:37 UTC, jereswaxd commented on app/src/main/res/layout/item_rv_us_about_us.xml
solucionado

2023-09-07 17:37 UTC, jereswaxd commented on app/src/main/java/com/example/refactoringlife4/model/service/UsService.kt
solucionado

2023-09-09 02:02 UTC, Emilce-Cano approved these changes

2023-09-09 02:03 UTC, Emilce-Cano approved these changes

2023-09-09 02:42 UTC, Milton0123 approved these changes

2023-09-09 02:43 UTC, merged