Feature/random dog
Milton0123/RefactoringLife4 pull request #62
Opened 2023-09-07 17:58 UTC by erikMaggio

![image](https://github.com/Milton0123/RefactoringLife4/assets/87202940/f98a2906-0660-4305-919d-ba91fe555951)

se creo consumo completo de random dog , mostrando una imagen de la lista por view

se implemento nuevo diseño al xml , se implemnento animacion en boton volver , y en la imagen huella , animacion y recarga de una nueva imagen

2023-09-07 18:01 UTC, Milton0123 requested changes

2023-09-07 18:01 UTC, Milton0123 commented on app/src/main/java/com/example/refactoringlife4/model/dto/RandomDogModel.kt
espacio en blanco

2023-09-07 18:01 UTC, Milton0123 commented on app/src/main/java/com/example/refactoringlife4/model/response/RandomDogResponse.kt
espacio en blanco

2023-09-09 01:59 UTC, Emilce-Cano requested changes

2023-09-09 01:59 UTC, Emilce-Cano commented on app/src/main/java/com/example/refactoringlife4/model/response/RandomDogResponse.kt
eso

2023-09-24 20:28 UTC, Emilce-Cano approved these changes

2023-09-24 21:26 UTC, merged